# Generated by Django 3.1 on 2022-10-20 03:23

from django.db import migrations
from django.contrib.auth.models import User


def load_invitees(apps, schema_editor):
    User_Team = apps.get_model('api', 'User_Team')
    first_director_id = User_Team.objects.filter(role__name='DIRECTOR').order_by('id').first()
    UserInvitee = User.objects.all()
    userinvitees = [person for person in UserInvitee if person.userprofile.status == "PENDING"]
    Invitee = apps.get_model('api', "Invitee")
    invitees = [Invitee(created_by_id=first_director_id.id, email=person.email) for person in userinvitees]
    Invitee.objects.bulk_create(

        invitees
    )


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_invitee'),
    ]

    operations = [
        migrations.RunPython(load_invitees)
    ]
