# Generated by Django 3.1 on 2023-05-23 18:41

from django.db import migrations


class Migration(migrations.Migration):

    def update_team_names(apps, schema_editor):
            team_model = apps.get_model('api', 'Team')
            team = team_model.objects.get(name="Tech Event Volunteers")
            team.name= "Tech Event Team"
            team.save()
            team = team_model.objects.get(name="Social Media")
            team.name= "Social Media Team"
            team.save()



    dependencies = [
        ('api', '0015_invitee'),
    ]

    operations = [
          migrations.RunPython(update_team_names),
    ]
