# Generated by Django 3.1 on 2023-06-02 02:08

from django.db import migrations
from django.contrib.auth.models import User


def delete_pending_users(apps, schema_editor):
    User = apps.get_model('auth', 'User')
    UserProfile = apps.get_model("api", "UserProfile")
    User_Team = apps.get_model("api", "User_Team")
    users = User.objects.all()
    userteams = User_Team.objects.all()

    userprofile_pending = UserProfile.objects.filter(status="PENDING")
    userprofile_pending_names = [people.user for people in userprofile_pending]
    for people in users:
        if people in userprofile_pending_names:
            people.delete()  # can this be a list comp?

    for people in userteams:
        if people.user in userprofile_pending_names:
            people.delete()  # can this be a list comp?

    UserProfile.objects.filter(status="PENDING").delete()

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20230523_1841'),
    ]

    operations = [
        migrations.RunPython(delete_pending_users),
    ]
