# Generated by Django 3.1 on 2023-05-28 23:26

from django.db import migrations
from api.models import Resource

class Migration(migrations.Migration):

    def add_host_management_resource(apps, schema_editor):
        new_resource = 'host_management_resource'
        edit_link = "https://docs.google.com/document/d/1REZR2zOp8pE8OMrnpeSRGS3K460OotSHsB5HXoSysfw/edit"
        pub_link = "https://docs.google.com/document/d/e/2PACX-1vST21FmmGPJq3Fn9jvpAHOVHfbt2celSabqQvAOlG2KTRVKVDEmqWZONKDqrn1Q-i0VP7r3rRyJyGZ3/pub?embedded=true"

        resource_model = apps.get_model('api', 'Resource')
        resource_list = resource_model.objects.values_list('slug', flat=True)
        if new_resource not in resource_list:
            Resource(slug=new_resource, edit_link=edit_link, published_link=pub_link).save()

    dependencies = [
        ('api', '0016_auto_20230523_1841'),
    ]

    operations = [
        migrations.RunPython(add_host_management_resource)
    ]
