# Generated by Django 3.2 on 2023-06-26 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_host_contact'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            ALTER TABLE "api_host" ALTER COLUMN "company" TYPE varchar(255) COLLATE "case_insensitive";
            ALTER TABLE "api_host" ADD UNIQUE(company);
            """,
            reverse_sql="",
            state_operations=[
                migrations.AlterField(
                    model_name='host',
                    name='company',
                    field=models.CharField(db_collation='case_insensitive', max_length=255, unique=True),
                ),
            ],
        ),
    ]
