# Generated by Django 3.2 on 2023-07-17 01:23

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_auto_20230712_2347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='Photo',
            field=models.ImageField(blank=True, null=True, upload_to=api.models.upload_to),
        ),
    ]
