# Generated by Django 3.2 on 2023-09-14 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_default_active_status_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mentor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('level', models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced')], max_length=20)),
                ('reliability', models.CharField(choices=[('Unknown', 'Unknown'), ('Poor', 'Poor'), ('Adequate', 'Adequate'), ('Good', 'Good'), ('Excellent', 'Excellent')], max_length=20)),
            ],
        ),
    ]
