# Generated by Django 3.2 on 2023-10-17 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_delete_registrationtoken'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invitee',
            name='accepted',
        ),
    ]
